FROM node:20 AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install
COPY . .
RUN npm run build


FROM nginx:alpine AS final

RUN rm /etc/nginx/conf.d/default.conf


COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]